### PR TITLE
Reading readme.txt as a file that contains utf-8.

### PR DESCRIPTION
**Pull request by dimazest**
Also reading the file inside of a context manager, as script installation might break on pypy when a lot of packages are being installed.

This brakes NLTK test installation for me...

### CODE REVIEW

**Comment by kmike** [comment]
I recall there was a problem: if you read non-ascii text as unicode then it doesn't work in Python 2.x, if you read it as bytes then it doesn't work in Python 3.x

**Comment by dimazest** [comment]
That's funny. 

Would it make sense to read the file differently depending on the python version?

**Comment by dimazest** [comment]
Should be fine now.

**Comment by kmike** [comment]
Thanks! I've just released text-unidecode 1.0; could you please confirm it works for you?

**Comment by dimazest** [comment]
Yes, NLTK tests work under both Python 2 and 3:
```
py27 installed: coverage==3.7.1,nltk==3.0.4,nose==1.3.7,numpy==1.9.2,text-unidecode==1.0,wheel==0.24.0

py34 installed: coverage==3.7.1,nltk==3.0.4,nose==1.3.7,numpy==1.9.2,scikit-learn==0.16.1,scipy==0.16.0,text-unidecode==1.0,wheel==0.24.0
```

**Comment by kmike** [comment]
great!

**Pull request merged**
